from __future__ import annotations

from .models import (
    AdoptionMetric,
    BusinessCaseMetric,
    DeliveryMetric,
    Experiment,
    FeedbackTheme,
    FacilitationItem,
    Guide,
    PowerBIView,
    ProgramSignal,
    ReadinessDimension,
    RoleFitCard,
    SupportChannel,
    TrainingSession,
    UseCase,
)


USE_CASES = [
    UseCase(
        id="finance-close-copilot-sprint",
        name="Finance Close Copilot Sprint",
        track="value-realization",
        audiences=["finance", "executive", "it"],
        summary="Role-based Copilot adoption sprint for month-end close, variance commentary, and post-close follow-up.",
        workflow="Copilot in Excel, Teams, and Outlook with manager review checkpoints and approved finance templates.",
        stakeholders=["Finance Controller", "M365 Platform Lead", "Change Manager"],
        owner="Copilot Adoption Office",
        rollout_wave="Wave 1: Korea, Singapore, United Kingdom",
        goals=[
            "Reduce meeting-to-summary turnaround during close week",
            "Standardize follow-up emails with approved financial language",
            "Measure hours saved and manager quality approval before scale-out",
        ],
        guardrails=[
            "Human review required for numeric interpretations and executive sends",
            "Approved templates only for board or audit-facing communication",
            "No external sharing or unsanctioned plugins during pilot",
        ],
        assets=[
            "finance_prompt_pack_v1",
            "quality_review_checklist",
            "Power BI wave dashboard",
        ],
        adoption_stage="pilot-ready",
    ),
    UseCase(
        id="legal-matter-prep-copilot-sprint",
        name="Legal Matter Prep Copilot Sprint",
        track="change-readiness",
        audiences=["legal", "executive", "it"],
        summary="Guided Copilot workflow for matter intake summaries, first-pass clause comparisons, and meeting recap drafting.",
        workflow="Copilot in Word and Teams with clause library references, human approval, and escalation to legal reviewers.",
        stakeholders=["General Counsel", "Compliance Lead", "Copilot Champion Lead"],
        owner="Legal Enablement Lead",
        rollout_wave="Wave 1: United States and Germany",
        goals=[
            "Shorten first-draft preparation time for internal legal reviews",
            "Reduce recap-writing effort after stakeholder meetings",
            "Document safe and unsafe patterns before wider rollout",
        ],
        guardrails=[
            "No autonomous legal advice or final redline generation",
            "All outputs remain draft material until attorney approval",
            "Sensitive matter names and regulated terms stay in approved repositories only",
        ],
        assets=[
            "legal_safe_use_standard",
            "attorney_review_gate",
            "decision_log_template",
        ],
        adoption_stage="assessment-running",
    ),
    UseCase(
        id="customer-service-resolution-drafting-sprint",
        name="Customer Service Resolution Drafting Sprint",
        track="training-and-champions",
        audiences=["customer-service", "champion", "it"],
        summary="Champion-led Copilot rollout for summarizing case context, drafting response options, and coaching agents on tone.",
        workflow="Copilot in Outlook and Teams with supervisor quality calibration, support macros, and multilingual guidance.",
        stakeholders=["Customer Service Director", "Helpdesk Lead", "Regional Champion Managers"],
        owner="Service Transformation Office",
        rollout_wave="Wave 2: Japan, Korea, Spain, Mexico",
        goals=[
            "Cut response drafting time for repeat issue categories",
            "Improve supervisor approval rate on AI-assisted responses",
            "Scale local champion support across time zones",
        ],
        guardrails=[
            "Agents must validate customer facts before send",
            "Escalation language stays aligned to regional compliance policies",
            "Quality reviewers sample outputs weekly during rollout",
        ],
        assets=[
            "response_quality_rubric",
            "champion_office_hours_pack",
            "multilingual_prompt_examples",
        ],
        adoption_stage="champion-cohort-live",
    ),
    UseCase(
        id="executive-briefing-recap-sprint",
        name="Executive Briefing and Decision Recap Sprint",
        track="adoption-analytics",
        audiences=["executive", "champion", "it"],
        summary="Executive assistant and chief-of-staff workflow for meeting recap drafts, action tracking, and decision-log hygiene.",
        workflow="Copilot in Teams, Word, and Loop with explicit ownership, parking lot notes, and follow-up deadlines.",
        stakeholders=["Chief of Staff", "Executive Sponsor", "Program Manager"],
        owner="Transformation PMO",
        rollout_wave="Wave 0: sponsor team and steering committee",
        goals=[
            "Improve decision velocity in steering forums",
            "Keep action owners and dates visible after each workshop",
            "Model trustworthy Copilot behavior for downstream business teams",
        ],
        guardrails=[
            "Decision notes are reviewed before broad distribution",
            "Parking lot items require owner and revisit date",
            "No meeting summary is treated as final without sponsor confirmation",
        ],
        assets=[
            "exec_readout_template",
            "meeting_timer_guide",
            "decision_log_canvas",
        ],
        adoption_stage="sponsor-live",
    ),
]

GUIDES = [
    Guide(
        id="guide-001",
        title="Copilot Readiness Assessment Playbook",
        audience="it",
        category="assessment",
        summary="ADKAR-aligned readiness checklist for sponsors, IT, security, and business leads before Copilot scale-up.",
        tags=["ADKAR", "Prosci", "readiness", "Copilot", "change"],
        path="docs/copilot_readiness_assessment.md",
        excerpt="Score awareness, desire, knowledge, ability, and reinforcement by persona before approving a new wave.",
        owner="Copilot Adoption Office",
        distribution=["steering packet", "project site", "wave gate review"],
        last_updated="2026-04-09",
    ),
    Guide(
        id="guide-002",
        title="Champion Community Launch Kit",
        audience="champion",
        category="training",
        summary="Operating model for champion recruitment, office hours, escalation, and local-language enablement at scale.",
        tags=["champions", "community", "training", "office hours", "scale"],
        path="docs/champion_launch_kit.md",
        excerpt="Each champion cohort has one playbook, one escalation route, one monthly spotlight, and one adoption target.",
        owner="Change Enablement Lead",
        distribution=["champion kickoff", "community site", "monthly digest"],
        last_updated="2026-04-09",
    ),
    Guide(
        id="guide-003",
        title="Prompt and Human Review Standard",
        audience="all",
        category="governance",
        summary="Practical standard for approved prompt patterns, quality checks, and when to require human approval.",
        tags=["prompt", "quality", "human review", "safety", "governance"],
        path="docs/prompt_review_standard.md",
        excerpt="Teach people when Copilot is a drafting accelerator and when it is only a starting point.",
        owner="Responsible AI Lead",
        distribution=["all-user portal", "training follow-up", "manager cascade"],
        last_updated="2026-04-09",
    ),
    Guide(
        id="guide-004",
        title="Multi-Geo Change Communications Pack",
        audience="executive",
        category="communications",
        summary="Messaging framework for multilingual launches, manager cascades, FAQ localization, and regional objections.",
        tags=["multi-geo", "multilingual", "communications", "manager", "rollout"],
        path="docs/multi_geo_change_comms.md",
        excerpt="Keep the global story consistent while allowing local examples, local office hours, and local support channels.",
        owner="Communications Lead",
        distribution=["manager toolkit", "regional launch pack", "FAQ site"],
        last_updated="2026-04-09",
    ),
    Guide(
        id="guide-005",
        title="Value Realization KPI Dictionary",
        audience="executive",
        category="analytics",
        summary="Definition set for adoption, quality, time saved, support, retention, and business value measures.",
        tags=["KPI", "Power BI", "adoption", "analytics", "value"],
        path="docs/value_realization_kpi_dictionary.md",
        excerpt="License activation is not enough; value requires repeat use, quality lift, and business-owner validation.",
        owner="Adoption Analytics Lead",
        distribution=["Power BI view", "exec readout", "weekly operating review"],
        last_updated="2026-04-09",
    ),
    Guide(
        id="guide-006",
        title="Facilitation, Parking Lot, and Decision Log Toolkit",
        audience="executive",
        category="facilitation",
        summary="Workshop operating guide for visible timers, objection handling, decision capture, and follow-through.",
        tags=["facilitation", "decision log", "parking lot", "objections", "timers"],
        path="docs/facilitation_toolkit.md",
        excerpt="Convert fear, safety, and quality objections into time-boxed experiments with owners and dates.",
        owner="Program Facilitator",
        distribution=["steering meetings", "working sessions", "interview appendix"],
        last_updated="2026-04-09",
    ),
    Guide(
        id="guide-007",
        title="JD Alignment Matrix",
        audience="executive",
        category="interview",
        summary="Bullet-by-bullet mapping of the Microsoft job description to concrete project evidence and honest proof boundaries.",
        tags=["JD", "alignment", "evidence", "interview", "Microsoft"],
        path="docs/jd_alignment_matrix.md",
        excerpt="Every required and preferred qualification is mapped to a project artifact, with explicit notes on what the project can and cannot prove.",
        owner="Candidate Portfolio",
        distribution=["interview packet", "portfolio appendix", "self-review"],
        last_updated="2026-04-09",
    ),
    Guide(
        id="guide-008",
        title="English Demo Script",
        audience="executive",
        category="interview",
        summary="Tight 7-minute English walkthrough for the second-round Microsoft interview.",
        tags=["demo", "English", "interview", "script", "walkthrough"],
        path="docs/demo_script_english.md",
        excerpt="Open with the business problem, show the role-fit board, run the planner, and close with the value and support model.",
        owner="Candidate Portfolio",
        distribution=["interview rehearsal", "self-review"],
        last_updated="2026-04-09",
    ),
    Guide(
        id="guide-009",
        title="STAR Story Bank",
        audience="executive",
        category="interview",
        summary="English STAR-style answers for consulting, facilitation, adoption, stakeholder alignment, and objection handling.",
        tags=["STAR", "behavioral", "English", "interview", "stakeholders"],
        path="docs/star_story_bank.md",
        excerpt="Use concise stories that show structure, ownership, and measurable outcomes without overstating experience.",
        owner="Candidate Portfolio",
        distribution=["interview rehearsal", "self-review"],
        last_updated="2026-04-09",
    ),
    Guide(
        id="guide-010",
        title="30-60-90 Day Plan",
        audience="executive",
        category="strategy",
        summary="How I would onboard into the role and create momentum in the first three months.",
        tags=["30-60-90", "onboarding", "strategy", "Copilot", "consulting"],
        path="docs/thirty_sixty_ninety_plan.md",
        excerpt="The plan starts with listening and discovery, then moves into pilot shaping, adoption instrumentation, and scale decisions.",
        owner="Candidate Portfolio",
        distribution=["interview packet", "follow-up email"],
        last_updated="2026-04-09",
    ),
]

PROGRAM_SIGNALS = [
    ProgramSignal(
        name="Weekly active usage in wave 1",
        status="healthy",
        metric="61%",
        owner="Adoption Analytics Lead",
        detail="Wave 1 trained users crossed the 60 percent weekly active threshold set for the first 30 days.",
    ),
    ProgramSignal(
        name="Four-week retention after training",
        status="watch",
        metric="72%",
        owner="Change Enablement Lead",
        detail="Repeat usage is improving but still below the 75 percent target for finance and legal cohorts.",
    ),
    ProgramSignal(
        name="Manager quality approval on AI-assisted drafts",
        status="healthy",
        metric="84%",
        owner="Business Process Owners",
        detail="Quality review remains above threshold when the standard prompt pack and review checklist are used.",
    ),
    ProgramSignal(
        name="Support ticket reopen rate",
        status="watch",
        metric="9%",
        owner="Helpdesk Lead",
        detail="Most reopen tickets relate to unclear prompt boundaries and need reinforcing through manager cascades.",
    ),
    ProgramSignal(
        name="Champion coverage across time zones",
        status="healthy",
        metric="94%",
        owner="Champion Community Manager",
        detail="Local-language office hours now cover all target regions except one late-evening handoff window.",
    ),
]

TRAINING_SESSIONS = [
    TrainingSession(
        title="Executive Sponsor Copilot Briefing",
        audience="executive",
        format="30-minute decision briefing",
        owner="Copilot Adoption Office",
        outcome="Align sponsors on scope, guardrails, success metrics, and the scale decision cadence.",
    ),
    TrainingSession(
        title="Finance and Legal Prompt Lab",
        audience="finance",
        format="60-minute live practitioner lab",
        owner="Business Change Lead",
        outcome="Teach prompt patterns, review gates, and what good AI-assisted work looks like in regulated teams.",
    ),
    TrainingSession(
        title="Customer Service Quality Calibration Clinic",
        audience="customer-service",
        format="45-minute coaching session",
        owner="Service Transformation Office",
        outcome="Calibrate response tone, approval criteria, and multilingual customer communications.",
    ),
    TrainingSession(
        title="Champion Office Hours Playbook",
        audience="champion",
        format="90-minute train-the-trainer",
        owner="Champion Community Manager",
        outcome="Prepare champions to unblock teams, capture feedback, and route risks quickly.",
    ),
    TrainingSession(
        title="Manager Cascade Toolkit Walkthrough",
        audience="it",
        format="recorded briefing plus FAQ pack",
        owner="Communications Lead",
        outcome="Give frontline managers a repeatable story for why Copilot is changing, how to use it, and how to escalate.",
    ),
]

READINESS_DIMENSIONS = [
    ReadinessDimension(
        name="Awareness",
        score_pct=88,
        owner="Executive Sponsor",
        status="healthy",
        action="Keep the sponsor message tied to one business problem and repeat it in the manager cascade.",
    ),
    ReadinessDimension(
        name="Desire",
        score_pct=74,
        owner="Change Enablement Lead",
        status="watch",
        action="Use business-unit success stories and manager coaching to convert curiosity into repeat use.",
    ),
    ReadinessDimension(
        name="Knowledge",
        score_pct=81,
        owner="Training Lead",
        status="healthy",
        action="Sustain role-based prompt labs and quick-reference guides for each wave.",
    ),
    ReadinessDimension(
        name="Ability",
        score_pct=69,
        owner="Business Process Owners",
        status="watch",
        action="Run guided practice with reviewed examples until managers confirm acceptable output quality.",
    ),
    ReadinessDimension(
        name="Reinforcement",
        score_pct=63,
        owner="Adoption Analytics Lead",
        status="watch",
        action="Close the loop with weekly KPI readouts, champion digests, and blocker reviews in steering.",
    ),
]

DELIVERY_METRICS = [
    DeliveryMetric(
        label="Priority personas",
        value="4",
        detail="Finance, legal, customer service, and executive staff are modeled separately instead of one generic rollout.",
    ),
    DeliveryMetric(
        label="Wave countries",
        value="12",
        detail="The scenario includes multi-geo sequencing and local-language support instead of a single-market pilot.",
    ),
    DeliveryMetric(
        label="Champion design capacity",
        value="1,200+ users",
        detail="Champion staffing, office hours, and escalation design assume large-enterprise scale.",
    ),
    DeliveryMetric(
        label="Power BI cadence",
        value="Daily refresh",
        detail="The KPI dictionary and dashboard narrative assume daily adoption and value readouts for sponsors.",
    ),
]

ADOPTION_METRICS = [
    AdoptionMetric(
        label="Time saved per active user",
        value="38 min/week",
        trend="+9 min",
        detail="Based on meeting recap, drafting, and follow-up workflows in finance and executive cohorts.",
    ),
    AdoptionMetric(
        label="Repeat use after first training",
        value="72%",
        trend="+6 pts",
        detail="Measured as users returning in week 2 and week 4 after guided enablement.",
    ),
    AdoptionMetric(
        label="Quality-approved AI drafts",
        value="84%",
        trend="+11 pts",
        detail="Supervisor or manager approval rate after prompt standardization and review checklists.",
    ),
    AdoptionMetric(
        label="Champion-solved issues",
        value="67%",
        trend="+14 pts",
        detail="Share of help questions resolved by the champion community before central support intervention.",
    ),
]

BUSINESS_CASE_METRICS = [
    BusinessCaseMetric(
        label="Finance recap package cycle time",
        baseline="52 min",
        target="32 min",
        owner="Finance Controller",
        value_case="Shorten close-week recap preparation while holding quality approval above threshold.",
    ),
    BusinessCaseMetric(
        label="Legal meeting recap drafting time",
        baseline="43 min",
        target="24 min",
        owner="General Counsel Delegate",
        value_case="Reduce internal recap effort so attorneys spend more time on review and judgment.",
    ),
    BusinessCaseMetric(
        label="Customer service response drafting time",
        baseline="16 min",
        target="9 min",
        owner="Customer Service Director",
        value_case="Improve agent throughput while preserving supervisor-approved tone and fact validation.",
    ),
    BusinessCaseMetric(
        label="Executive follow-up note turnaround",
        baseline="6 hrs",
        target="90 min",
        owner="Chief of Staff",
        value_case="Speed up decision follow-through by turning meetings into visible actions with owners and dates.",
    ),
]

POWER_BI_VIEWS = [
    PowerBIView(
        name="Sponsor scorecard",
        audience="executive",
        purpose="One-page view of readiness, adoption, quality, and scale recommendation for the weekly steering committee.",
        primary_kpis=["weekly active use", "repeat use", "quality approval", "time saved"],
    ),
    PowerBIView(
        name="Persona adoption cockpit",
        audience="it",
        purpose="Compare finance, legal, customer service, and executive cohorts by wave, region, and support load.",
        primary_kpis=["repeat use", "support reopen rate", "champion-solved issues", "manager approval"],
    ),
    PowerBIView(
        name="Champion operations board",
        audience="champion",
        purpose="Track office-hours demand, unresolved blockers, FAQ themes, and community participation by region.",
        primary_kpis=["office-hours attendance", "champion-solved issues", "unresolved blockers", "FAQ aging"],
    ),
]

SUPPORT_CHANNELS = [
    SupportChannel(
        name="Copilot in-product guidance",
        tier="tier-0",
        owner="M365 Platform Lead",
        sla="Immediate self-serve",
        purpose="Direct users to safe-use tips, approved prompt patterns, and launch FAQs before a ticket is raised.",
        languages=["English", "Korean", "Japanese"],
    ),
    SupportChannel(
        name="Champion office hours",
        tier="tier-1",
        owner="Champion Community Manager",
        sla="Same business day",
        purpose="Resolve routine usage questions, capture blockers, and reinforce role-based scenarios.",
        languages=["English", "Korean", "Spanish", "Japanese"],
    ),
    SupportChannel(
        name="Central adoption helpdesk",
        tier="tier-2",
        owner="Helpdesk Lead",
        sla="24 hours",
        purpose="Handle access, prompt-quality, and launch-communications issues that champions cannot close alone.",
        languages=["English"],
    ),
    SupportChannel(
        name="Security and compliance escalation",
        tier="tier-3",
        owner="Responsible AI Lead",
        sla="48 hours",
        purpose="Review policy-sensitive questions, regulated workflows, and region-specific safety concerns.",
        languages=["English"],
    ),
]

FEEDBACK_THEMES = [
    FeedbackTheme(
        theme="Managers need stronger quality coaching examples",
        source="Office hours and post-training survey",
        volume="High",
        owner="Training Lead",
        next_action="Publish two reviewed before-and-after examples and add them to the manager toolkit.",
    ),
    FeedbackTheme(
        theme="Legal teams want clearer boundaries for draft versus decision work",
        source="Legal pilot retrospective",
        volume="Medium",
        owner="Compliance Lead",
        next_action="Expand the safe-use standard with legal-specific review checkpoints.",
    ),
    FeedbackTheme(
        theme="Regional users need better multilingual FAQ coverage",
        source="Helpdesk reopen tickets",
        volume="Medium",
        owner="Communications Lead",
        next_action="Add Korean, Japanese, and Spanish FAQ variants before wave 2 launch.",
    ),
    FeedbackTheme(
        theme="Champions need a faster blocker-escalation path",
        source="Champion community sync",
        volume="Low",
        owner="Adoption Success Manager",
        next_action="Introduce a weekly blocker triage with adoption, support, and platform leads.",
    ),
]

ROLE_FIT_CARDS = [
    RoleFitCard(
        requirement="Copilot AI usage readiness assessments and action plans",
        proof="The project includes an ADKAR-aligned readiness playbook, wave gates, persona-based scoring, and next-step recommendations.",
        artifacts=["docs/copilot_readiness_assessment.md", "/api/overview", "/api/assistant/plan"],
    ),
    RoleFitCard(
        requirement="Training development and champion enablement at enterprise scale",
        proof="Role-based curricula, champion launch assets, multilingual support patterns, and office-hour operating design are built in.",
        artifacts=["docs/champion_launch_kit.md", "src/App.tsx", "/api/overview"],
    ),
    RoleFitCard(
        requirement="Adoption analytics, KPI interpretation, and Power BI-style value views",
        proof="Adoption metrics, program signals, and the KPI dictionary show how to move from seat counts to measurable business impact.",
        artifacts=["docs/value_realization_kpi_dictionary.md", "/api/overview", "src/App.tsx"],
    ),
    RoleFitCard(
        requirement="Feedback mechanisms, support systems, and blocker removal with adoption/success teams",
        proof="The project models tiered support, feedback themes, champion escalation, and weekly blocker reviews instead of treating support as an afterthought.",
        artifacts=["/api/overview", "src/App.tsx", "docs/feedback_support_operating_model.md"],
    ),
    RoleFitCard(
        requirement="Deep enablement for finance, legal, and customer service personas",
        proof="The scenario portfolio explicitly separates finance, legal, customer service, and executive workflows so each persona has its own value case and guardrails.",
        artifacts=["/api/use-cases", "src/App.tsx", "docs/copilot_business_case_playbook.md"],
    ),
    RoleFitCard(
        requirement="Multi-geo, multilingual rollout and internal communications",
        proof="The program includes geo-specific waves, local-language support, communications packs, and rollout packet checks for localization readiness.",
        artifacts=["docs/multi_geo_change_comms.md", "src/App.tsx", "/api/rollout-packet/preview"],
    ),
    RoleFitCard(
        requirement="Exec and practitioner facilitation with decision log and objection handling",
        proof="The facilitation toolkit, visible decision board, and objection-to-experiment tracker keep meetings outcome-focused.",
        artifacts=["docs/facilitation_toolkit.md", "src/App.tsx", "/api/assistant/plan"],
    ),
    RoleFitCard(
        requirement="Cross-functional change leadership across business, IT, and executives",
        proof="Every use case explicitly maps business owners, IT owners, governance checks, support channels, and sponsor readouts.",
        artifacts=["/api/overview", "docs/role_fit.md", "docs/interview_storyline.md"],
    ),
]

FACILITATION_ITEMS = [
    FacilitationItem(
        title="Approve wave 2 customer service launch language",
        kind="decision",
        owner="Regional Change Lead",
        due_date="2026-04-18",
        status="needs sponsor decision",
        note="Two markets want stronger tone guidance before expanding multilingual response drafting.",
    ),
    FacilitationItem(
        title="Non-M365 plugin requests",
        kind="parking-lot",
        owner="M365 Platform Lead",
        due_date="2026-04-22",
        status="parked for architecture review",
        note="Keep the first 90 days focused on standard Copilot workflows before adjacent tooling debates.",
    ),
    FacilitationItem(
        title="Steering committee timer",
        kind="timer",
        owner="Program Facilitator",
        due_date="Every weekly steering",
        status="active",
        note="10 minutes for decision review, 15 minutes for blocker removal, 5 minutes for the parking lot sweep.",
    ),
    FacilitationItem(
        title="Value readout for CFO and GC",
        kind="readout",
        owner="Adoption Analytics Lead",
        due_date="2026-04-29",
        status="drafting",
        note="Show repeat usage, quality lift, and documented hours saved before proposing legal expansion.",
    ),
]

OBJECTION_LOG = [
    Experiment(
        concern="AI fear: teams think Copilot will replace judgment rather than accelerate drafting.",
        hypothesis="If we teach draft-versus-decision boundaries and show manager-reviewed examples, repeat use will rise without trust erosion.",
        owner="Change Enablement Lead",
        target_date="2026-04-24",
        success_metric="Increase repeat usage by 5 points while keeping manager quality approval above 82 percent.",
    ),
    Experiment(
        concern="Quality objection: finance managers distrust AI-generated summaries during close week.",
        hypothesis="If we constrain prompts to approved templates and add a short review checklist, approval rates will stay above threshold.",
        owner="Finance Controller",
        target_date="2026-04-19",
        success_metric="Maintain 85 percent approval on AI-assisted follow-up drafts in the pilot cohort.",
    ),
    Experiment(
        concern="Safety objection: regional teams worry multilingual prompts will create policy drift.",
        hypothesis="If we localize examples and require region-specific FAQ review, support reopen rates will fall.",
        owner="Communications Lead",
        target_date="2026-04-26",
        success_metric="Reduce reopen tickets tied to language ambiguity from 9 percent to 6 percent.",
    ),
]

SAMPLE_REQUESTS = [
    "We need an English-language briefing for a global Copilot rollout in finance and legal, including readiness, training, and value KPIs.",
    "Customer service leaders are worried about quality and multilingual consistency. Build a champion-led experiment plan with owners and dates.",
    "Our executive sponsor wants a 30-day business case for Microsoft 365 Copilot with decision logs, support model, and Power BI adoption views.",
    "A regional IT lead wants to know if the next wave is ready for launch and what objections must be converted into experiments first.",
]
