from __future__ import annotations

import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from backend.app.data import (  # noqa: E402
    ADOPTION_METRICS,
    BUSINESS_CASE_METRICS,
    DELIVERY_METRICS,
    FEEDBACK_THEMES,
    FACILITATION_ITEMS,
    GUIDES,
    OBJECTION_LOG,
    POWER_BI_VIEWS,
    PROGRAM_SIGNALS,
    READINESS_DIMENSIONS,
    ROLE_FIT_CARDS,
    SAMPLE_REQUESTS,
    SUPPORT_CHANNELS,
    TRAINING_SESSIONS,
    USE_CASES,
)


def overview_summary() -> dict[str, int]:
    healthy_count = sum(1 for item in PROGRAM_SIGNALS if item.status == "healthy")
    readiness_score = int((healthy_count / len(PROGRAM_SIGNALS)) * 100)
    return {
        "use_case_count": len(USE_CASES),
        "guide_count": len(GUIDES),
        "healthy_signal_count": healthy_count,
        "readiness_score": readiness_score,
    }


def main() -> None:
    overview = {
        "summary": overview_summary(),
        "delivery_metrics": [item.model_dump() for item in DELIVERY_METRICS],
        "adoption_metrics": [item.model_dump() for item in ADOPTION_METRICS],
        "readiness_dimensions": [item.model_dump() for item in READINESS_DIMENSIONS],
        "business_case_metrics": [item.model_dump() for item in BUSINESS_CASE_METRICS],
        "power_bi_views": [item.model_dump() for item in POWER_BI_VIEWS],
        "support_channels": [item.model_dump() for item in SUPPORT_CHANNELS],
        "feedback_themes": [item.model_dump() for item in FEEDBACK_THEMES],
        "role_fit": [item.model_dump() for item in ROLE_FIT_CARDS],
        "sample_requests": SAMPLE_REQUESTS,
        "use_cases": [item.model_dump() for item in USE_CASES],
        "guides": [item.model_dump() for item in GUIDES],
        "program_signals": [item.model_dump() for item in PROGRAM_SIGNALS],
        "training_sessions": [item.model_dump() for item in TRAINING_SESSIONS],
        "facilitation_items": [item.model_dump() for item in FACILITATION_ITEMS],
        "objection_log": [item.model_dump() for item in OBJECTION_LOG],
    }

    guide_details: dict[str, dict[str, object]] = {}
    for guide in GUIDES:
        guide_path = ROOT / guide.path
        guide_details[guide.id] = {
            "guide": guide.model_dump(),
            "body": guide_path.read_text(encoding="utf-8"),
        }

    output_path = ROOT / "cloudflare" / "generated" / "static-data.ts"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "\n".join(
            [
                "/* Auto-generated by scripts/export_cloudflare_data.py. */",
                f"export const overview = {json.dumps(overview, ensure_ascii=False, indent=2)} as const;",
                f"export const guideDetails = {json.dumps(guide_details, ensure_ascii=False, indent=2)} as const;",
                "",
            ]
        ),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
